[build]
  functions = "node_modules/cmless/api/"
  publish = "node_modules/cmless/build/"
  command = "cd node_modules/cmless && npm run build"

[build.environment]
  NODE_VERSION = "14.17.6"

# Disabled until preserving query parameters is implemented:
# https://community.netlify.com/t/preserve-query-parameters-on-redirect/2226/24
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
